// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghstncypfsyhjaqixgpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdoc3RuY3lwZnN5aGphcWl4Z3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NzM2NDAsImV4cCI6MjA4ODA0OTY0MH0.DxCh5d1wg7kS2hfe8-6LAbOoIoiKdl9hrxGbzVZORCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});